export const types = Object.freeze({
  TRACKER_START_FETCHING: "TRACKER_START_FETCHING",
  TRACKER_STOP_FETCHING: "TRACKER_STOP_FETCHING",
  TRACKER_SET_FETCHING_ERROR: "TRACKER_SET_FETCHING_ERROR",
  TRACKER_FILL_RECORD: "TRACKER_FILL_RECORD",
  TRACKER_FILL_SCORE: "TRACKER_FILL_SCORE",
  TRACKER_RESET: "TRACKER_RESET",
});
